[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
automatic_auction = "HMmKpGJBCdmCp9XMv4YVrnYppr1c5Wi36ptVTXGfs75y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/timi/Downloads/wallet-keypair(1).json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
